config/routes.rb
Rails.application.routes.draw do
  get 'searchs/search'
  devise_for :users
   root to: 'homes#top'
   get 'home/about' => 'homes#about'
  resources :users,only: [:show,:index,:edit,:update]do
    member do
     get :following, :followers
    end
  end
  resources :books,only: [:new, :create, :index, :show, :edit, :update, :destroy]do
  resources :post_comments, only: [:create, :destroy]
  resource :favorites, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  get '/search', to: 'searchs#search'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
   attachment :profile_image, destroy: false

   attachment :profile_image
          validates :name, presence: true
          validates :name, uniqueness: true
          validates :name, length: { in: 2..20 }
          validates :introduction,length: { maximum: 50 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new

  end

  def edit
    @user = User.find(params[:id])
    if @user!=current_user
    redirect_to user_path(current_user)
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def following
      @user  = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.followings.count %></td>
        <td>フォロワー数:<%= user.followers.count %></td>

        <!---フォロー機能-->
        <% unless current_user == user %>
        <% if current_user.following?(user) %>
        <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
        <%= hidden_field_tag :follow_id, user.id %>
         <td><%= f.submit 'Unfollow', class: 'btn btn-danger ' %> </td>
        <% end %>
          <% else %>
          <%= form_for(current_user.relationships.build) do |f| %>
          <%= hidden_field_tag :follow_id, user.id %>
           <td><%= f.submit 'Follow', class: 'btn btn-primary ' %> </td>
          <% end %>
        <% end %>
      <% end %>
       <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag user,:profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
</table>

<div class='row'>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>
<%= link_to  following_user_path(user) do %>
<p>フォロー数<%= user.followings.count %></p>
<% end %>
<%= link_to  followers_user_path(user) do %>
<p>フォロワー数<%= user.followers.count %></p>

<% end %>
<%= render 'relationships/follow_button', user: user %>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book  %>
    </div>
    <div class='col-md-8 offset-md-1'>
    <h2>Users</h2>
    <%= render 'index',users: @users %>
    </div>
 </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user, book: @book %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<% @user.followings.each do |user| %>
<table>
   <tr><h1>Follow Users</h1></tr>
<tr>
  <td><h4>image</h4></td>
  <td><h4>name</h4></td>
</tr>
<tr>
   <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
  <td>  <%= user.name %> </td>
  <td>フォロー数:<%= @user.followings.count %></td>
  <td>フォロワー数:<%= @user.followers.count %></td>
  <td><%= link_to 'Show', user_path(user) %></td>
</tr>

</table>
<% end %>

app/views/users/show_follower.html.erb
<% @user.followers.each do |user| %>
<table>
  <tr><h1>Follower Users</h1></tr>
<tr>
  <td><h4>image</h4></td>
  <td><h4>name</h4></td>
</tr>
<tr>
   <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
  <td>  <%= user.name %> </td>
  <td>フォロー数:<%= @user.followings.count %></td>
  <td>フォロワー数:<%= @user.followers.count %></td>
  <td><%= link_to 'Show', user_path(user) %></td>
</tr>

</table>
<% end %>