config/routes.rb
Rails.application.routes.draw do
  get 'searchs/search'
  devise_for :users
   root to: 'homes#top'
   get 'home/about' => 'homes#about'
  resources :users,only: [:show,:index,:edit,:update]do
    member do
     get :following, :followers
    end
  end
  resources :books,only: [:new, :create, :index, :show, :edit, :update, :destroy]do
  resources :post_comments, only: [:create, :destroy]
  resource :favorites, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  get '/search', to: 'searchs#search'
end

app/models/book.rb
class Book < ApplicationRecord
	 belongs_to :user
	 has_many :post_comments, dependent: :destroy
     has_many :favorites, dependent: :destroy

	def favorited_by?(user)
    	favorites.where(user_id: user.id).exists?
	end
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @books = Book.all
    @user = @book.user
    @post_comment = PostComment.new
    @post_comments = @book.post_comments
    @favorite = Favorite.new



  end

  def index
    @book = Book.new
    @books = Book.all
    @user = @book.user
    @favorite = Favorite.find_by(book_id: params[:book_id], user_id: current_user.id)
    @favorites = Favorite.all

  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
     if @book.user==current_user
     render "edit"
     else
     redirect_to books_path
     end
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.user==current_user
      @book.destroy
      redirect_to books_path
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body )
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <% if book.errors.any? %>
　 <p>2 errors prohibited this book from being saved:</p>
     <% book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
  <% end %>
  <% end %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
         <td id="favorites_buttons_<%= book.id %>">
             <%= render partial: 'favorites/favorite', locals: { book: book} %>
        </td>

        <td> <td><p>コメント件数：<%= book.post_comments.count %></p></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', books: @books,book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books, book: @book, users: @users%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', book: @book , book_new: @book_new, user: @book.user%>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book_new  %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		      <%= link_to user_path(@book.user) do %>
             <td><%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br><%= @book.user.name %> </td>
            <% end %>
            <td> <%=@book.title%> </td>
            <td> <%=@book.body%> </td>

           <% if user_signed_in? && @book.user.id == current_user.id %>
          <td><%=  @book.title  %></td>
          <td><%= @book.body %></td>
          <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
          <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
            <% end %>

        <!--いいね-->
        <td id="favorites_buttons_<%= @book.id %>">
        <%= render partial: 'favorites/favorite', locals: { book: @book} %>
        </td>
       </table>
        <table id="comments_index_<%= @book.id %>">
             <%= render partial: 'post_comments/index', locals: { post_comment: @post_comment, book: @book} %>
        </table>
      <%= form_with(model:[@book, @post_comment]) do |f| %>
      <%= f.text_area :comment %>
      <div>
      <%= f.submit "送信する" %>
      </div>
      <% end %>
      </div>
    </div>
  </div>
   <!--コメント一覧-->